# Generated by Django 4.1.6 on 2023-03-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задачи', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date_todo',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='state',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Выполняется'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='todo',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='todos', to='webapp.position'),
        ),
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='todo', to='webapp.type', verbose_name='Type'),
        ),
    ]
